/**
  * Solitaire Scorpion
  * Deck.java
  * @version    1.0     2021-11-16
  * @author     Soumil Verma 
  * Creates an array of 52 cards based on an input String[]
  * Deal a single card at a time using drawCard()
  * this will be used to populate the game board
  * @param args[0] accepts all scanned input (via FileReader)
  * @return a functioning (or shuffled) deck 
  * Also, drawCard method populates deck to the tableau.java class
  * toString method is used to print the deck
  */
public class Deck {
    private Card[] cards;
    private String[] deck;
    private int currentCard;
  /**
    * Deck class constructor
    * @param is accepts cards from main
    * @return card stored in array.
    */
    public Deck(String[] is){
        this.deck = is;
        currentCard = 0;
        this.cards = new Card[is.length];
        for(int j = 0; j < cards.length; j++) {
            String rawOfCard = is[j];
            Card card = new Card(rawOfCard);   
            cards[j] = card;
        }
    }
  /**
    * Method to shuffle deck and reset currentCard deck counter counter.
    * @return shuffled deck.
    */
    public void shuffle() {
        for(int i = 0; i < deck.length; i++) {
            int swap = i + (int) (Math.random() * (deck.length-i));
            String temp = deck[swap];
            deck[swap] = deck[i];
            deck[i] = temp;
        }
        currentCard = 0;
    }
    //gives a card out of deck - will be used to draw cards to list (populate game board)
    public String drawCard() {
        String s = deck[currentCard];
        currentCard++;
        return s;
    }
  /**
    * Getter and setter methods automatically generated by Eclipse
    * @param deckOfCards accepts a deck of cards via array
    * @return returns deck
    * @return returns card
    * @return sets deck = deck of Cards
    */ 
    public String[] getDeck() { return deck; }
    public void setDeck(String[] deckOfCards) { this.deck = deckOfCards; }
    public Card[] getCard() { return cards; }
  /**
    * prints cards
    * @return information of card to tableau.class
    */
    public String toString() {
        String s = "";
        for(int j = 0; j < deck.length; j++) { s += deck[j] + " "; }
        return s;
    }
}