/**
  * Solitaire Scorpion
  * Card.java
  * @version    1.0     2021-11-16
  * @author     Soumil Verma 
  * Creates an array of 52 cards based on an input String[]
  * Deal a single card at a time using drawCard()
  * this will be used to populate the game board
  * @param card accepts card value as string
  * @return a numerical value of card
  */
public class Card {
    private String rank;
    private char suit;
    private boolean isFaceUp = true;
    private int rankNum;
  /**
    * Checks whether is corerct card or not and assigns it a rank
    * @param card as string
    * @return card value and assigns as rank, if invalid throws exception error
    */  
    public Card(String card) {
        if(card.length() == 2) {					//Ex: 5D
            this.rank = "" + card.charAt(0);
            this.suit = card.charAt(1);
            this.rankNum = toInt(rank);
        }
        else if(card.length() == 3) {				//Ex: 10D
            this.rank = "" + card.charAt(0) + card.charAt(1);
            this.suit = card.charAt(2);
            this.rankNum = toInt(rank);;
        }else {
            throw new IllegalArgumentException("Bad Card " + card);
        }
    }
  /**
    * Gets value to card and convert to a numerical value.
    * @param rank accepts a String card value
    * @return an integer of card value
    */  
    private static int toInt(String rank) {
        if(rank.equals("K")) { return 13; }
        if(rank.equals("Q")) { return 12; }
        if(rank.equals("J")) { return 11; }
        if(rank.equals("A")) { return 1; }
        return Integer.parseInt(rank);
    }
  /**
    * Getter and setter methods automatically generated by Eclipse
    * Will be used by tableau.java for processing
    * @param rank of card
    * @param f set card faceup
    * @param suit suit value of card
    * @param ranNum card numerical value
    * @return an integer of card value
    * @return whether card is faceup or not
    * @return value of card
    * @return card numerical value as a rank
    */ 
    public String getRank() { return rank; }
    public void setFaceUp(boolean f) { isFaceUp = f; }
    public char getSuit() { return suit; }
    public boolean isFaceUp() { return isFaceUp; }
    public int getRankNum() { return rankNum; }
  /**
    * toString method returns value of card, suit, faceup condition, and rank number
    * @return information of card to tableau.class
    */ 
    @Override
    public String toString() { return "Card [rank=" + rank + ", suit=" + suit + ", isFaceUp=" + isFaceUp + ", rankNum=" + rankNum + "]"; }
}